server:
  port: 9999

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://13.237.197.3:3306/doggy?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username : doggy-care-user
    password : 1234

mybatis:
  config-location: classpath:/config/SqlMapConfig.xml
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: com.service.spring.vo
